# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: "dc=example,dc=com"
                search_dn: "cn=read-only-admin,dc=example,dc=com"
                search_password: "password"
                default_roles: ROLE_USER
                uid_key: uid
                filter: "(uid=%s)"

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\UserRegistrationAuthenticator
                - App\Security\LdapAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/ooredoo/admin, roles: [ROLE_ADMIN] }
        - { path: ^/ooredoo, roles: [ROLE_CLOUD, ROLE_ASEVAS, ROLE_ASEIN, ROLE_ASEGPRS, ROLE_Backup, ROLE_BILLING] }

when@test:
    security:
        role_hierarchy:
            ROLE_ADMIN: [ROLE_CLOUD, ROLE_ASEVAS, ROLE_ASEIN, ROLE_ASEGPRS, ROLE_Backup, ROLE_BILLING]
            ROLE_CLOUD: [ROLE_USER]
            ROLE_ASEVAS: [ROLE_USER]
            ROLE_ASEIN: [ROLE_USER]
            ROLE_ASEGPRS: [ROLE_USER]
            ROLE_Backup: [ROLE_USER]
            ROLE_BILLING: [ROLE_USER]
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
